### ISSUE TITLE
MyGroups: not all groups show up

### ISSUE THREAD

**Issue by hismightiness** [hismightiness/dnnextensions#11]
Hi

I am using the module on the profile page and not all of the groups that I belong to show up. Most do. Is there criteria that is used to determine what groups are selected? Also, is there is easy way to show the page link instead just a picture?

I am not a developer but can figure some things out :)

Thank you

carl

ORIGINAL: https://dnnmygroups.codeplex.com/workitem/13397

**Comment by teambound** [comment]
UPDATE

I found out what the problem is. If a group role is defined as "BOTH" group and normal, all groups do not show up. I it is changed to just group role then they show up ok

**Comment by hismightiness** [comment]
It should work with that condition.  So, I'll get that updated soon.
