### ISSUE TITLE
Bug: Modal Screen to submit session

### ISSUE THREAD

**Issue by jncraig** [hismightiness/dnnextensions#117]
It is narrow. Doesn't seem to have controls to widen it.

**Comment by hismightiness** [comment]
It shouldn't be narrow. Please update the issue with a screenshot and any details you have about your skin.

**Comment by jncraig** [comment]
I was using the old Gravity skin on the page.  I switched to Xcillion and an Xcillion container.  Much better!  Now ... how the heck does one spell Xcillion?

**Comment by hismightiness** [comment]
Please view the skin/theme requirements mentioned in the documentation.

https://github.com/hismightiness/dnnextensions/wiki/Documentation-Code-Camp-Events-General
