### ISSUE TITLE
CodeCamp: Time slots

### ISSUE THREAD

**Issue by jncraig** [hismightiness/dnnextensions#120]
Is there a starting time that cannot be violated?  I wanted to start breakfast at 7 am, but it's adding an hour to the times I specify.

and 8 am is converted to 9 am ...

**Comment by nvisionative** [comment]
@hismightiness this seems to be an issue with angular-moment.  You can use the following filter to see what timezone is being used.  

``
amDateFormat: 'hh:mm A z'
``

Then, if necessary, consider storing dates in UTC and then converting to local time client side using something like the following:

``
{{timeSlot.BeginTime | amUtc | amLocal | amDateFormat:'hh:mm A'}}
``

**Comment by hismightiness** [comment]
Are we talking about the beginning time being changed automatically? Can you please be more specific on the steps that were used to create a result and what the undesired result was?

**Comment by jncraig** [comment]
Enter 8'am as the starting tome and save.  The display says 9 am.

**Comment by hismightiness** [comment]
I'm not trying to be difficult, just making sure I know the steps to duplicate the issue.

- Create/edit time slot
- Choose a start time of 8:00 AM [unknown end time]
- Save the time slot
- View the time slot in [unknown view] and the start time is 9:00 AM

**Comment by jncraig** [comment]
The ending times behave the same way.

**Comment by nvisionative** [comment]
We have yet to be able to replicate this issue.  @jncraig I know it has been a while since you looked into this, but do you remember anything specific that could help us to recreate the behavior you were experiencing?  Thanks!

**Comment by jncraig** [comment]
What is the issue?

**Comment by nvisionative** [comment]
Unable to reproduce or get further clarification.  Will re-open if issue resurfaces.
