### ISSUE TITLE
CodeCamp: Time slots

### ISSUE THREAD

**Issue by jncraig** [hismightiness/dnnextensions#121]
In creating time slots, if I want something to start at 8 am, I have to enter 7 am.  It seems to be the same for all times.

Also, is it possible to have different schedules for a 2-day event?  It appears that's not the case.

**Comment by nvisionative** [comment]
@hismightiness see notes on #120 for local time offset issue.

@jncraig I am not sure about the ability to have different schedules for a 2-day event.

**Comment by hismightiness** [comment]
Time slots have nothing to do with the days of the event, just the time slots available in each day.  You define the number of days by defining the begin and end dates in the event information on the event homepage.

**Comment by jncraig** [comment]
What if I want different schedules one the two days?  That is, the time
slots for Friday are different than on Saturday.

**Comment by nvisionative** [comment]
Unable to reproduce or get further clarification.
