### ISSUE TITLE
Content Slider is not compatible with DNN8

### ISSUE THREAD

**Issue by ainsofsoo** [hismightiness/dnnextensions#122]
Hi,
I installed your module on a fresh install of DNN8 and added it to the page. When I add a slide I get an error : 
`Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Unknown server tag 'dnn:DnnDatePicker'.`

I think the "dnn:DnnDatePicker" control is no longer available in DNN 8.

**Comment by simoales** [comment]
Same issue here. Any solution planned?

**Comment by hismightiness** [comment]
The solution is pretty easy... it's basically a rebuild and updated reference for DNN 8 only.  Anyone willing with the skills to perform a pull request?

**Comment by nvisionative** [comment]
@hismightiness if somebody hasn't done this by next week, I'll be happy to.  :)

**Comment by simoales** [comment]
@nvisionative could you do it? I'd be grateful...

All the best

Simone

**Comment by simoales** [comment]
Any news about that? If somebody could send me a few lines (or links) of instruction I'd be glad to help.

**Comment by nvisionative** [comment]
@simoales sorry for the delayed response.  We had a lot going on around DNNCon and are still getting settled back in here.  I was able to clone the project and rebuild with the proper references to DNN 8.  Here are the Install and Source packages for you.

[WillStrohl.CodeCamp_01.00.02_Install.zip](https://github.com/hismightiness/dnnextensions/files/213949/WillStrohl.CodeCamp_01.00.02_Install.zip)
[WillStrohl.CodeCamp_01.00.02_Source.zip](https://github.com/hismightiness/dnnextensions/files/213948/WillStrohl.CodeCamp_01.00.02_Source.zip)

@hismightiness I would be happy to create a pull request if that were applicable, but there is really nothing to change in the code.  It just needed to be recompiled against DNN 8.

**Comment by nvisionative** [comment]
@simoales - I apologize.  I sent packages for the wrong extension.  The ContentSlider extension turns out to not be so straight forward, but I believe @hismightiness is working on it.

**Comment by hismightiness** [comment]
https://github.com/hismightiness/dnnextensions/releases/tag/ContentSlider-01.03.00

**Comment by simoales** [comment]
Thank you, worked like a breeze!
