### ISSUE TITLE
Lightbox Gallery - Unknown server tag 'dnnweb:DnnComboBox'.

### ISSUE THREAD

**Issue by JaySMa** [hismightiness/dnnextensions#125]
Trying to add new album on DNN 8.0.3.  Getting the above error.

**Comment by hismightiness** [comment]
Just to be clear, you went to the view and saw the error, or you clicked on something and then saw it?  Also, which version of the module?

**Comment by hismightiness** [comment]
Fixed:
https://github.com/hismightiness/dnnextensions/releases/tag/Lightbox-01.12.00

**Comment by JaySMa** [comment]
Thank you.. I'll upgrade and test on our Evoq 8.4.2 box and let you know.
