### ISSUE TITLE
CodeCamp: Module requires search skin object in theme.

### ISSUE THREAD

**Issue by ralphwilliams** [hismightiness/dnnextensions#150]

**Comment by hismightiness** [comment]
Thanks for the issue.  This doesn't seem to be necessary in a clean installation of 7.4.2 or 8.0.3.  Would you happen to be using any other third party extensions that might be getting in the way?

**Comment by ralphwilliams** [comment]
I am using a clean install of v 8.0.4 and a third party skin. I can also reproduce this issue when using Gravity or the new Xcillion skin and remove the search skin objects from the skins. See attached for the errors in the console.

![image](https://cloud.githubusercontent.com/assets/5560203/18152427/bda756ba-6fc3-11e6-8436-c4b8f8d007ea.png)

**Comment by hismightiness** [comment]
@ralphwilliams Thanks for the very thorough update.

**Comment by hismightiness** [comment]
You welcome.

**Comment by nvisionative** [comment]
Thank you!

**Comment by ralphwilliams** [comment]
Thank your!

**Comment by nvisionative** [comment]
And thank you're!
