### ISSUE TITLE
Lightbox Gallery: How do I install? (DNN Newbie)

### ISSUE THREAD

**Issue by paulshryock** [hismightiness/dnnextensions#151]
I just downloaded the Lightbox Gallery Install ZIP latest release from GitHub, and unzipped it. Should I drop this folder into my DNN extensions folder? How do I get up and running?

I checked the documentation, but it's empty.

Thanks!

**Comment by hismightiness** [comment]
Hello:

Thanks for using the module and for your issue.  You'll find that installing any extension is generally the same, and really easy (as long as the developer/vendor is good).  

[http://www.dnnsoftware.com/community/learn/video-library/view-video/video/542/view/details/how-to-install-a-module-in-dotnetnuke-7](http://www.dnnsoftware.com/community/learn/video-library/view-video/video/542/view/details/how-to-install-a-module-in-dotnetnuke-7)

**Comment by hismightiness** [comment]
Please let me know if you need anything else.  Otherwise, I'll be closing the issue.
