### ISSUE TITLE
Add a download link!

### ISSUE THREAD

**Issue by VashJuan** [hismightiness/dnnextensions#163]
One thing SourceForge had over GitHub was a clear tab for downloading the latest install. 

Github is great for developers who want to dive into source code, but geeze, why don't they put in an obvious link for downloading? So maybe I'm clueless and missing something obvious, but I'd suggest you put a clear and easy-to-find download link right at the top of the first page, after a brief description of the module (something many github projects lack!).

 Isn't that the most common user story: people arriving to get a copy to install the extension on their website? Only experts need to see issues, documentation, source code, roadmap, etc. etc.: most folks just want to download the zip file - and it rarely is obvious in GitHub. 

(Sorry to rant!)

**Comment by ralphwilliams** [comment]
I agree that GitHub is lacking in pushing that to the top. But, releases can be easily found under the Releases Tab. This is really more of a GitHub issue than an issue for this open source project.

![image](https://cloud.githubusercontent.com/assets/5560203/19693283/f27eb152-9aa8-11e6-92d2-cd5342f4db31.png)

**Comment by VashJuan** [comment]
Fine, but I sure woudl not have found that without your guidence to go to the "releases" tab. For a generic admin looking at DNN's Extensions page, he/she sees an 'update available' link for Content Slider. Cool! 

Clicking it leads to DNN Forge. No downloads there. One has to then go to GitHub (why should a newbie admin have to know what github is all about?!) 

The one winds up at a page for dnnextensinos, not content slider, and then one has to figure out the "releases" tab (that's where I failed), and go search along it to find the prize.

Maybe its just me, but I suspect other admins are also frustrated and finding 'pain' just trying to get the up-to-date zip files.

Maybe put a link near the top of the home page on github's landing page?!

**Comment by hismightiness** [comment]
@VashJuan Thanks for your feedback.  You're spot on with a lot of the "issues" in discovering extensions in DNN these days.  Unfortunately, nearly every single bit of it is outside of our control, and is more in the control of Github and DNN Corp.  Github was already discussed here, but sometimes DNN's own integration with DNN Forge doesn't work as expected.  All I can do as the project owner is update the package information there (which I do).  After that, everything else is out of my hands.  Sorry.

**Comment by VashJuan** [comment]
Thanks Will & Ralph, I just needed to belly-ache!

Thanks for doing so much for the community! It is greatly appreciated.

**Comment by hismightiness** [comment]
It's our pleasure @VashJuan ... we try
