### ISSUE TITLE
DNN.Media module

### ISSUE THREAD

**Issue by JaySMa** [hismightiness/dnnextensions#168]
Doing searches for the module takes you do the codeplex website; http://dnnmedia.codeplex.com

Since this is going away, it links here.  But I haven't seen anything here which allows me to download a release of the latest version.

Is this module pretty much dead?

**Comment by nvisionative** [comment]
I don't think this module is dead, but a release of it does appear to be missing.  Perhaps @hismightiness can help?

**Comment by hismightiness** [comment]
It's not dead.  I just moved it to its own repo in the DNN Community org.  Please feel free to post any issues you wish there.

https://github.com/DNNCommunity/DNN.Media
