### ISSUE TITLE
Rearranging Album not working

### ISSUE THREAD

**Issue by digitalsigi** [hismightiness/dnnextensions#177]
Hi,
we are running Lightbox Gallery 1.12.0 on DNN 9.3.2 and quite happy with it. Thx for this piece of Software!
Only Issue: When rearranging the Album Order, the submit button does not work. Just nothing happens, no entry in Eventlog. 
What can I do to get more information and solve problem?
Josef

**Comment by digitalsigi** [comment]
Updated to DNN 9.4.1, still same problem. But now I got an error entry in Eventlog. See attached file.
Josef
[errorlog.zip](https://github.com/hismightiness/dnnextensions/files/3801506/errorlog.zip)

**Comment by digitalsigi** [comment]
Got some more Info:
JQMIGRATE: jQuery.fn.bind() is deprecated
JQMIGRATE: jQuery.unique is deprecated, use jQuery.uniqueSort
not found: DesktopModules/WillStrohl.LightBoxGallery/js/images/ui-bg_glass_40_111111_1x400.png

and more.
How to overcome this? 
To be honest, I have no working DNN development environment....
Plse help.

**Comment by edisfera** [comment]
There is a jQuery error complaining about .live not being a function (and this is preventing the two buttons from working). 
I fixed the error buy replacing .live with .on in the following files located in /DesktopModules/WillStrohl.LightboxGallery: ChangeImageOrder.ascx (lines 26 and 39), ChangeOrder.ascx (lines 26 and 39) and the problem was solved.

**Comment by digitalsigi** [comment]
Thx a lot for this! This is already an improvement, but now the two buttons are not visible and the Image is displayed as full screen.

**Comment by edisfera** [comment]
I did the same changes on my website and had no problem with buttons and images... if you change the .on back to .live does it revert back the button and image issue?

**Comment by hismightiness** [comment]
Wow... It's great to see that people are still using this module.  I had no idea!  :D  

I'll take a look into this as soon as I can.

**Comment by digitalsigi** [comment]
> I did the same changes on my website and had no problem with buttons and images... if you change the .on back to .live does it revert back the button and image issue?

OK. Rearraning works now.
However I am running DNN 9.4.1 and digging futher into problem I found that I was talking about another problem which is related to showing the gallery. There I have two issues:

1. jquery.fancybox-1.3.4.pack.js:18 Uncaught TypeError: Cannot read property 'msie' of undefined
2. Uncaught TypeError: jQuery(...).fancybox is not a function

See attached browser log
[www.burckhardia.at-1599643512569.log](https://github.com/hismightiness/dnnextensions/files/5194368/www.burckhardia.at-1599643512569.log)

What can I do to fix this?

**Comment by edisfera** [comment]
I am running on DNN 9.6.1 and the version of fancybox is 3.5.7. If I were you I would update DNN first to a more recent version to see if this fixes the problem and/or update fancybox to a later version. Alternatively you can also wait for Will to look in to the original issue and see if he can address this issue too in the fix.

**Comment by digitalsigi** [comment]
@edisfera Thx for followup. 
I came to same conclusion, I'll first update, and see what the result is.
@hismightiness Yeah, the members of our club like it. They can upload their pictures and have a simple and nice gallery ...

**Comment by hismightiness** [comment]
This issue was much more than just changing the jQuery method.  It took all day today and I thought I'd be done in an hour.  🤣 

https://github.com/hismightiness/dnnextensions/releases/tag/LBGallery-01.13.00

Thanks again for using the module and reporting the issue!

**Comment by digitalsigi** [comment]
@hismightiness Thx a lot for your effort. It works. 
Will there be another update for DNN 9.6+?
